<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>

    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>

    <RootNamespace>GameUpdateStatus</RootNamespace>
    <AssemblyName>GameUpdateStatus</AssemblyName>

    <LangVersion>latest</LangVersion>

    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>

    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="Playnite.SDK">
      <HintPath>C:\Users\Yann\AppData\Local\Playnite\Playnite.SDK.dll</HintPath>
    </Reference>

    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />

  </ItemGroup>

  <ItemGroup>
    <None Update="extension.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Playnite\**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

</Project>