<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>

    <OutputType>Library</OutputType>

    <RootNamespace>GameUpdateStatus</RootNamespace>
    <AssemblyName>GameUpdateStatus</AssemblyName>

    <LangVersion>latest</LangVersion>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />

    <PackageReference Include="PlayniteSDK"
                      Version="6.0.0" />

  </ItemGroup>

  <ItemGroup>
    <Page Include="Controls\UpdateStatusControl.xaml" />
  </ItemGroup>

</Project>